import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from './components/AuthProvider';
import { Session } from 'next-auth';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Iprops {
  children: React.ReactNode,
  session: Session
}

export default function RootLayout({
  children,
  session
}: Iprops) {
  return (
    <html lang="en">
      <body>
        <AuthProvider session={session}>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
